# Generated by Django 5.0.1 on 2024-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlAjuste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=600, null=True)),
                ('costo', models.CharField(blank=True, max_length=20, null=True)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_contrato',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='id_staff',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Contrato',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
