# Generated by Django 5.0.1 on 2024-01-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlAjuste', '0002_servicio_remove_pago_id_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre',
            new_name='nombre_servicio',
        ),
    ]
