# Generated by Django 5.0.1 on 2024-01-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlClientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
